[package]
name = "hello-teo-handlers"
version = "0.1.0"
edition = "2021"
 
[dependencies]
teo = { version = "0.3.1" }
tokio = { version = "1.0", features = ["full"] }
chrono = { version = "0.4" }
bson = { version = "2.9.0" }
bigdecimal = { version = "=0.3.1" }
indexmap = { version = "2.2.6" }
